#!/bin/bash

# Si el primer argumento es --configure, ejecuta el script src/configure.py y si no ejecuta el script src/main.py
if [ "$1" == "--configure" ]; then
    /home/$USER/Developer/Github/TermianlIA/.venv/bin/python /home/$USER/Developer/Github/TermianlIA/src/configure.py 
elif [ "$1" == "--telebot" ]; then
    /home/$USER/Developer/Github/TermianlIA/.venv/bin/python /home/$USER/Developer/Github/TermianlIA/src/telebot.py
else    
    /home/$USER/Developer/Github/TermianlIA/.venv/bin/python /home/$USER/Developer/Github/TermianlIA/src/main.py "$@" 
fi
